# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 18:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name="Author's first name.")),
                ('last_name', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name="Author's last name.")),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name="Author's email id.")),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_borrowed_date', models.DateTimeField(auto_now_add=True, verbose_name='Most reccent borrow date for this copy.')),
                ('book_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('available', models.BooleanField(default=True, verbose_name='Book availability.')),
            ],
        ),
        migrations.CreateModel(
            name='Book_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN of the book.')),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Title of the book.')),
                ('no_of_copies', models.IntegerField(default=1, verbose_name='Total number of copies available.')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Book deletion status')),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='Book addition date')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Book details modified date')),
                ('misc_details', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Extra details of book.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.Author', verbose_name='Unique id of the book author.')),
            ],
        ),
        migrations.CreateModel(
            name='BookAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Borrowed date.')),
                ('due_date', models.DateTimeField(verbose_name='Borrowed date.')),
                ('is_returned', models.BooleanField(default=False, verbose_name='Book return status.')),
                ('fine_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Fine collected.')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.Book', verbose_name='Id of the book copy issued.')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name="Member's first name.")),
                ('last_name', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name="Member's last name.")),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name="Member's email id.")),
                ('password', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='To store the encrypted password.')),
                ('phone', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telephone number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Member active status')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Member deletion status')),
                ('joined_on', models.DateTimeField(auto_now_add=True, verbose_name='Member joining date')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Member details modified date')),
                ('member_type', models.CharField(default='A', max_length=1, verbose_name='Member type. Admin/User')),
                ('expires_on', models.DateField(verbose_name='Membership expiry date.')),
                ('misc_details', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Membership miscellaneous details.')),
            ],
        ),
        migrations.AddField(
            model_name='bookaction',
            name='member',
            field=models.ManyToManyField(to='crud.Member', verbose_name='Member id of the user.'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Book_master', verbose_name='Id of the parent book.'),
        ),
    ]
