# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, unique=True, verbose_name="Author's email id."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='last_borrowed_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Most reccent borrow date for this copy.'),
            preserve_default=False,
        ),
    ]
