# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20180207_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_master',
            old_name='author_id',
            new_name='author',
        ),
    ]
