# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20180207_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_master_id',
            new_name='book_master',
        ),
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
